import JSZip from "jszip";
import { saveAs } from "file-saver";

/**
 * Generates a standalone ZIP for the landing page.
 * @param {string} html - The raw body HTML (or full document).
 * @param {string} title - The site title.
 */
export async function downloadStandaloneSite(html, title = "My LaunchPage AI") {
    const zip = new JSZip();
    let finalHtml = html;

    // 1. Fetch DaisyUI CSS for offline support (optional optimization)
    // We try to replace the CDN link with a local file for better performance/offline usage
    const daisyCdnLink = "https://cdn.jsdelivr.net/npm/daisyui@4.12.10/dist/full.min.css";
    try {
        const res = await fetch(daisyCdnLink);
        if (res.ok) {
            const daisyCss = await res.text();
            zip.folder("styles").file("daisyui.css", daisyCss);

            // Replace CDN link with local path
            finalHtml = finalHtml.replace(daisyCdnLink, "styles/daisyui.css");
        }
    } catch (e) {
        console.warn("Could not fetch DaisyUI for ZIP, keeping CDN link.");
    }

    // 2. Create the ZIP structure
    // We DO NOT wrap the HTML again because renderHtml returns a full <!DOCTYPE html> document.
    // We DO NOT strip scripts because Tailwind Play CDN is required for styling.

    zip.file("index.html", finalHtml);

    // Create a README explaining the tech stack
    zip.file("README.txt", `
Title: ${title}
Generated by: LaunchPage AI

Instructions:
1. Unzip the folder.
2. Open 'index.html' in any modern web browser.
3. Edit the text directly in the HTML file or upload to a hosting provider.

Tech Stack:
- TailwindCSS (via CDN script)
- DaisyUI (included in styles/ or via CDN)
- Google Fonts (Heebo)
    `.trim());

    // 3. Generate and Save
    const content = await zip.generateAsync({ type: "blob" });
    saveAs(content, `${title.replace(/\s+/g, '_')}_site.zip`);
}
