/**
 * Validates AI-generated HTML against strict quality, safety, and structure rules.
 * @param {string} htmlString - The raw HTML generated by the AI.
 * @returns {{ isValid: boolean, errors: string[] }}
 */
export function validateHtml(htmlString) {
    if (!htmlString || typeof htmlString !== 'string') {
        return { isValid: false, errors: ["Missing HTML content"] };
    }

    const errors = [];
    const lowerHtml = htmlString.toLowerCase();

    // 1. Structure Checks
    if (!lowerHtml.includes("<html") || !lowerHtml.includes("<head") || !lowerHtml.includes("<body")) {
        errors.push("Missing core HTML structure (html, head, or body tags)");
    }

    const h1Matches = htmlString.match(/<h1[^>]*>([\s\S]*?)<\/h1>/gi);
    if (!h1Matches || h1Matches.length !== 1) {
        errors.push("Must contain exactly one <h1> tag");
    }

    // 2. CTA Verification
    const ctaKeywords = ["צור", "התחל", "דבר", "צור קשר"];
    const hasButton = htmlString.match(/<button/i);
    const links = htmlString.match(/<a[^>]*>([\s\S]*?)<\/a>/gi) || [];
    const hasCtaLink = links.some(link => ctaKeywords.some(keyword => link.includes(keyword)));

    if (!hasButton && !hasCtaLink) {
        errors.push("Missing a clear Call to Action (button or link with keywords)");
    }

    // 3. Quality & Length
    // Helper to strip tags for text evaluation
    const stripTags = (str) => (str || "").replace(/<[^>]*>?/gm, "").trim();

    // H1 length
    const h1Text = h1Matches ? stripTags(h1Matches[0]) : "";
    if (h1Text.length < 10) {
        errors.push("H1 headline is too short (minimum 10 characters)");
    }

    // Total text length
    const totalVisibleText = stripTags(htmlString);
    if (totalVisibleText.length < 300) {
        errors.push("Total visible text is too sparse (minimum 300 characters)");
    }

    // Paragraph sanity (walls of text)
    const paragraphs = htmlString.match(/<p[^>]*>([\s\S]*?)<\/p>/gi) || [];
    const wallOfText = paragraphs.some(p => stripTags(p).length > 400);
    if (wallOfText) {
        errors.push("Content contains paragraphs that are too long (walls of text)");
    }

    // 4. Safety Checks
    if (lowerHtml.includes("<script")) {
        errors.push("Unsafe content detected: <script> tags are forbidden");
    }

    const eventHandlers = [
        "onclick=", "onload=", "onerror=", "onmouseover=", "onsubmit=",
        "onfocus=", "onblur=", "onchange=", "onkeydown=", "onkeyup="
    ];
    if (eventHandlers.some(handler => lowerHtml.includes(handler))) {
        errors.push("Unsafe content detected: inline event handlers are forbidden");
    }

    if (lowerHtml.match(/src\s*=\s*['"]\s*javascript:/i) || lowerHtml.match(/href\s*=\s*['"]\s*javascript:/i)) {
        errors.push("Unsafe content detected: javascript pseudo-protocols are forbidden");
    }

    // 5. Design Sanity
    const hasDesignMarkers =
        lowerHtml.includes('class="container"') ||
        lowerHtml.includes('class="section"') ||
        lowerHtml.includes('<section');

    if (!hasDesignMarkers) {
        errors.push("Design sanity check failed: Missing structure classes or section tags");
    }

    return {
        isValid: errors.length === 0,
        errors
    };
}
